### ISSUE TITLE
standard steper library with limited functionality

### ISSUE THREAD

**Issue by rafaelpac** [tardate/X113647Stepper#1]
Hi!
You said that "it is possible to drive the X113647 board with the standard Stepper library - albeit with limited functionality".
What are these limitations?
I am using it and I don't see anything wrong...
Thanks!!!

**Comment by tardate** [comment]
hi @rafaelalvespereira oh, been a long time since I looked at this!

I think the issue was getting to control it in half-steps.
[SinglePhaseSweepWithStepperLibrary.ino](https://github.com/tardate/X113647Stepper/blob/master/examples/SinglePhaseSweepWithStepperLibrary/SinglePhaseSweepWithStepperLibrary.ino) was the standard Stepper library version, and [FullSweep](https://github.com/tardate/X113647Stepper/blob/master/examples/FullSweep/FullSweep.ino) using the X113647Stepper library.

Mind you, I had a sample size of 1 when playing with the X113647, so maybe there are different versions out there that don't behave the same way as mine.

**Comment by tardate** [comment]
@rafaelalvespereira I just had a deeper look at things stepper-related and came back to revisit this library. I think it is largely redundant now, but I've refreshed it anyway - especially the commentary in https://github.com/tardate/X113647Stepper/blob/master/README.md - and left the library here as an exercise in half (or other) step control.
